apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint-only-defaults
  namespace: kube-public
spec:
  limits:
    - default: # 此处定义默认限制值
        cpu: 500m
        memory: 512Mi
      type: Container
